# Preanálisis de los datos y pruebas para la limpieza de datos

In [1]:
# Importaciones
import pandas as pd
import numpy as np

#Seteo de opciones
pd.set_option("display.max_columns", None)

In [2]:
# Leemos el archivo
df_raw = pd.read_parquet("../data/data_raw/iowa_liquor_sales_2019.parquet")
df_raw.head()

Invoice/Item Number        Date  Store Number  \
102        S08792800017  11/06/2019          2459   
103        S04854100048  04/03/2019          2487   
106        S08900500035  11/13/2019          4509   
110        S06855800032  07/31/2019          2522   
113        S08372100023  10/16/2019          3816   

                               Store Name  \
102                        Reinhart Foods   
103                  Anamosa Family Foods   
106                       A J'S LIQUOR II   
110  Hy-Vee Wine and Spirits / Spirit Lak   
113                                 Swils   

                                        Store Location  County Number  \
102        200 STATE PO BOX 98\nGUTHRIE CENTER 50115\n           39.0   
103  402 EAST MAIN\nANAMOSA 52205\n(42.108289, -91....           53.0   
106  2515 CHAMBERLAIN\nAMES 50010\n(42.02146, -93.6...           85.0   
110                HWY 9 &amp; 71\nSPIRIT LAKE 51360\n           30.0   
113  200 E OAK ST\nRED OAK 51566\n(41.016691, -95.2...           69.0   

         County   Category                       Category Name  Vendor Number  \
102     Guthrie  1062300.0                        FLAVORED RUM           65.0   
103       Jones  1081300.0                 PEPPERMINT SCHNAPPS          434.0   
106       Story  1081900.0  MISC. AMERICAN CORDIALS & LIQUEURS          322.0   
110   Dickinson  1062200.0    PUERTO RICO & VIRGIN ISLANDS RUM           35.0   
113  Montgomery  1031200.0                      VODKA FLAVORED          380.0   

                         Vendor Name  Item Number           Item Description  \
102                  Jim Beam Brands        44499           Cruzan Mango Rum   
103                   Luxco-St Louis        80578  Arrow Peppermint Schnapps   
106  Prestige Wine and Spirits Group        75210              Kinky Liqueur   
110             Bacardi U.S.A., Inc.        43125   Bacardi Superior Rum Pet   
113        Phillips Beverage Company        41693  Uv Blue (raspberry) Vodka   

     Pack  Bottle Volume (ml) State Bottle Cost State Bottle Retail  \
102    12                 750             $6.82              $10.24   
103     6                1750             $7.04              $10.56   
106     6                 750            $10.00              $15.00   
110    12                 750             $7.53              $11.30   
113    12                 750             $6.25               $9.49   

     Bottles Sold Sale (Dollars)  Volume Sold (Gallons)  
102             3         $30.72                   0.59  
103             3         $31.68                   1.39  
106            12        $180.00                   2.38  
110            12        $135.60                   2.38  
113            12        $113.88                   2.38

In [3]:
# Primero una copia del df por si acaso
df = df_raw
print(f"El dataset esta formado por {df.shape[0]} filas y {df.shape[1]} columnas")

El dataset esta formado por 2073616 filas y 20 columnas


In [4]:
# Convertimos el nombre de las col en snake_case
df.columns = df.columns.str.replace(" ","_").str.lower().str.replace("_(", "(")
df.sample(3)


invoice/item_number        date  store_number  \
3723158        S06784300037  07/26/2019          3912   
57604          S04379700016  03/05/2019          2599   
762071         S08173600007  10/08/2019          2623   

                                   store_name  \
3723158  Smokin' Joe's #14 Tobacco and Liquor   
57604    Hy-Vee Wine and Spirits / Coralville   
762071      Hy-Vee Food Store #4 / Sioux City   

                                            store_location  county_number  \
3723158  225 EDGEWOOD RD\nCEDAR RAPIDS 52405\n(41.97341...           57.0   
57604    1914 8TH STREET\nCORALVILLE 52241\n(41.682013,...           52.0   
762071   2827 HAMILTON BLVD\nSIOUX CITY 51104\n(42.5198...           97.0   

           county   category    category_name  vendor_number  \
3723158      Linn  1012300.0   IRISH WHISKIES          370.0   
57604     Johnson  1081030.0  COFFEE LIQUEURS          259.0   
762071   Woodbury  1032080.0   IMPORTED VODKA          260.0   

                              vendor_name  item_number  \
3723158  Pernod Ricard USA/Austin Nichols        15644   
57604                  Heaven Hill Brands        67426   
762071                    Diageo Americas        34457   

                   item_description  pack  bottle_volume(ml)  \
3723158                     Jameson    24                375   
57604    Copa De Oro Mexican Coffee    12                750   
762071     Ketel One Imported Vodka    12               1000   

        state_bottle_cost state_bottle_retail  bottles_sold sale(dollars)  \
3723158             $6.35               $9.53             1         $9.53   
57604               $4.63               $7.27            12        $87.24   
762071             $17.00              $25.49            24       $611.76   

         volume_sold(gallons)  
3723158                  0.10  
57604                    2.38  
762071                   6.34

In [5]:
# Cambiamos el nombre a la columna category 
df.rename(columns={"category":"category_number"}, inplace=True)

In [6]:
df.columns

Index(['invoice/item_number', 'date', 'store_number', 'store_name',
       'store_location', 'county_number', 'county', 'category_number',
       'category_name', 'vendor_number', 'vendor_name', 'item_number',
       'item_description', 'pack', 'bottle_volume(ml)', 'state_bottle_cost',
       'state_bottle_retail', 'bottles_sold', 'sale(dollars)',
       'volume_sold(gallons)'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2073616 entries, 102 to 8197504
Data columns (total 20 columns):
 #   Column                Dtype  
---  ------                -----  
 0   invoice/item_number   object 
 1   date                  object 
 2   store_number          int64  
 3   store_name            object 
 4   store_location        object 
 5   county_number         float64
 6   county                object 
 7   category_number       float64
 8   category_name         object 
 9   vendor_number         float64
 10  vendor_name           object 
 11  item_number           int64  
 12  item_description      object 
 13  pack                  int64  
 14  bottle_volume(ml)     int64  
 15  state_bottle_cost     object 
 16  state_bottle_retail   object 
 17  bottles_sold          int64  
 18  sale(dollars)         object 
 19  volume_sold(gallons)  float64
dtypes: float64(4), int64(5), object(11)
memory usage: 332.2+ MB


## Transformación de datos

### Columna de fecha

In [8]:
# Convertimos a formato datetime
df["date"] = pd.to_datetime(df["date"],format = "%m/%d/%Y" )                                   

### Columnas float a integers: las relacionadas con el numero

In [9]:
df["county_number"].unique()

array([39., 53., 85., 30., 69., 57., 82., 96., 77., 31., 78., 52.,  9.,
       64., 49., 29., 34., 48., 63., 75., 97., 22., 46., 91.,  7., 70.,
       94., 10., 11., 56., 17., 71., 23., 50., 14., 67., 37., 86., 88.,
       40., 59., 51., 33., nan, 38., 72., 16., 21., 42., 35.,  3., 47.,
       90., 24.,  4., 95.,  6., 55., 20., 99., 32.,  5., 81., 45., 62.,
       25., 83., 60., 54., 41., 18., 84., 92., 28., 93.,  1., 44., 13.,
       58., 66.,  8., 15., 76., 79., 74., 19., 43., 12.,  2., 61., 73.,
       80., 65., 68., 87., 27., 36., 98., 89., 26.])

In [10]:
df["category_number"].unique()

array([1062300., 1081300., 1081900., 1062200., 1031200., 1012100.,
       1042100., 1701100., 1011100., 1041100., 1062310., 1082900.,
       1032200., 1011200., 1032080., 1071100., 1031080., 1031100.,
       1011300., 1052010., 1081600., 1012200., 1101100., 1081200.,
       1051110., 1051100., 1011500., 1022100., 1062050., 1051010.,
       1081370., 1051150., 1081400., 1081365., 1081340., 1081390.,
       1081330., 1081240., 1051120., 1081315., 1012210., 1081015.,
       1081305., 1081317., 1081312., 1081350., 1081335., 1062100.,
       1041150., 1081030., 1081220., 1012300., 1081380., 1081500.,
       1081010., 1081355., 1081700., 1031110., 1011250., 1031090.,
       1081230., 1041200., 1081250., 1051140., 1011400., 1022200.,
       1081210.,      nan, 1081020., 1082010., 1062250., 1032100.,
       1032230., 1082015., 1501100., 1082390.])

In [11]:
df["vendor_number"].unique()

array([ 65., 434., 322.,  35., 380., 260., 370., 192.,  55.,  85., 297.,
       389., 115., 451., 305., 395., 255., 461., 330., 420., 259., 410.,
       421., 885., 300., 205., 308., 240., 306., 357., 971., 294., 130.,
       390., 969., 301., 125., 277., 375., 267., 384., 418., 394., 365.,
       190., 285., 184., 338., 350., 492., 391., 198., 469.,  86., 160.,
       460., 962., 377., 978., 483., 239., 977., 250., 497., 495., 346.,
       399.,  89.,  10., 459., 295., 293., 154., 298., 158.,  91., 465.,
       415., 503.,  79., 369., 363., 987., 143., 307., 185., 224., 109.,
       211., 310., 379., 477.,  90., 108., 313.,  61., 278., 501., 251.,
        80., 311., 482., 456., 137., 361., 475., 287., 488.,  27., 485.,
       803.,  68., 432., 263., 155.,  69., 343., 161., 486.,  51.])

### Despues de comprobar los valores unicos, vemos que no tiene sentido que los valores sean float, deberían ser int. Pasamos a transformarlos en la columna que podemos porque no tiene nulos

In [12]:
# df["county_number"] = df["county_number"].astype(int) ---no funciona porque hay valores Nan
#df["county_number"] = df["county_number"].apply(lambda x: int(x) if pd.notnull(x) else np.nan)--- tampoco funciona

In [13]:
df["vendor_number"] = df["vendor_number"].astype(int)

In [14]:
df["vendor_number"].unique()

array([ 65, 434, 322,  35, 380, 260, 370, 192,  55,  85, 297, 389, 115,
       451, 305, 395, 255, 461, 330, 420, 259, 410, 421, 885, 300, 205,
       308, 240, 306, 357, 971, 294, 130, 390, 969, 301, 125, 277, 375,
       267, 384, 418, 394, 365, 190, 285, 184, 338, 350, 492, 391, 198,
       469,  86, 160, 460, 962, 377, 978, 483, 239, 977, 250, 497, 495,
       346, 399,  89,  10, 459, 295, 293, 154, 298, 158,  91, 465, 415,
       503,  79, 369, 363, 987, 143, 307, 185, 224, 109, 211, 310, 379,
       477,  90, 108, 313,  61, 278, 501, 251,  80, 311, 482, 456, 137,
       361, 475, 287, 488,  27, 485, 803,  68, 432, 263, 155,  69, 343,
       161, 486,  51])

### Transformar los valores de las columnas de precio :
- `state_bottle_cost`
- `state_bottle_retail`
- `sale(dollars)`

In [15]:
precio_limpiar = df["state_bottle_cost"].iloc[0]
precio_limpiar

'$6.82'

In [16]:
#df["state_bottle_cost"]=df["state_bottle_cost"].str.replace("$", "").astype(float)

In [17]:
def dollars_float(dataframe,col):
     dataframe[col] = dataframe[col].str.replace("$", "").astype(float)
     return dataframe

In [18]:
lista_col = ["state_bottle_cost", "state_bottle_retail", "sale(dollars)"]
for col in lista_col:
     dollars_float(df,col)

### Descomposición de la columna `store_location`

In [19]:
valor_store_location = df["store_location"].iloc[1]
valor_store_location

'402 EAST MAIN\nANAMOSA 52205\n(42.108289, -91.281881)'

In [20]:
# addres = valor_store_location.split("\n")[0]
# city = valor_store_location.split("\n")[1].split()
# latitud = float(valor_store_location.split("\n")[2].strip("()").split(",")[0])
# longitud =float(valor_store_location.split("\n")[2].strip("()").split(", ")[1]) 

In [21]:
def extract_location(valor):
     try:
          split_data = valor.split("\n") # el split genera una lista
          adress = split_data[0]
          city = split_data[1]
          if len(split_data)> 2 and split_data[2].strip():
               latitude, longitude = map(float,split_data[2].strip("()").split(", ")) # aqui genero otra lista
          else:
              latitude, longitude = None, None 
          return pd.Series([adress, city, latitude, longitude])
     except(IndexError, ValueError):
          return pd.Series([None, None, None, None])

In [22]:
df[["adress", "city", "latitude", "longitude"]] = df["store_location"].apply(extract_location)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2073616 entries, 102 to 8197504
Data columns (total 24 columns):
 #   Column                Dtype         
---  ------                -----         
 0   invoice/item_number   object        
 1   date                  datetime64[ns]
 2   store_number          int64         
 3   store_name            object        
 4   store_location        object        
 5   county_number         float64       
 6   county                object        
 7   category_number       float64       
 8   category_name         object        
 9   vendor_number         int64         
 10  vendor_name           object        
 11  item_number           int64         
 12  item_description      object        
 13  pack                  int64         
 14  bottle_volume(ml)     int64         
 15  state_bottle_cost     float64       
 16  state_bottle_retail   float64       
 17  bottles_sold          int64         
 18  sale(dollars)         float64       
 19  vol

In [23]:
df.to_parquet("../data/data_transform/dataset_cleaned.parquet")